### ISSUE TITLE
1.04.0300 released

### ISSUE THREAD

**Issue by LOVECHEN** [CunningLogic/DUMLRacer#4]
can you made a new version to support this if you have time ,thank you

**Comment by CunningLogic** [comment]
Have you confirmed it doesnt work?

**Comment by CunningLogic** [comment]
DUMLRacer works fine on 1.4.03

If root is not triggering for you, then you may wish to repack payload2 and target another hijack point.

**Comment by LOVEChen** [comment]
tested can't downupgrade
