### ISSUE TITLE
Is this were I get help for using DUMLRacer?

### ISSUE THREAD

**Issue by serpa4** [CunningLogic/DUMLRacer#5]
Good evening. I"m trying to use DUMLRacer.jar to downgrade my Mavic Pro Platinum to 1.04.0100 and its not working.
1st, thanks
2nd, I know "nothing" about coding, scrips, etc.  I followed a youtube video, but didn't work.
https://www.youtube.com/watch?v=ywUUoYcPvt8

I have done everything through the DOS prompt, but get to:
Choose target Port.
[1] COM4 : USB Serial Device (COM4)
[E] Exit.
When I choose the port by entering 1, I get the following prompt:
Choose target port: (* suggested port)
[1] COM4 : USB Serial Device (COM4)
[E] Exit
Choose port: 1
Using Port: COM4
Couldn't open port, exiting
Sending upgrade command

What is going wrong with my comm port? Says Couldn't open port, exiting.
I have my Mavic plugged in via USB. It is recognized by assistant 2 v1.1.2 and 1.2.0
Under device manager, it shows a comport appearing when I plug in the Mavic:
USB Serial Device (COM4)

Device is working properly.
9600 bits per second
Driver: Microsoft 6/21/2006. V 10.0.16299.15

This is my 4th or 5th attempt with the same results.
On the first attempt I got through successfully, and it said completed. I then restarted my Mavic and tried to use DUMLdore 1.14 to go back to 1.04.0100
However, I get this popup and it only exits and never does anything.

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Could not load file or assembly ‘WinSCPnet, Version=1.3.7.7601. Culture=neutral. PublicKey Token=2271ec4a3c56dbf’ or one of its dependencies. The system cannot find the file specified.exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Could not load file or assembly ‘WinSCPnet, Version=1.3.7.7601. Culture=neutral. PublicKey Token=2271ec4a3c56dbf’ or one of its dependencies. The system cannot find the file specified.

Any suggestions?
Thanks!!

**Comment by CunningLogic** [comment]
Well kinda, it is a place to get help with issues with DUMLRacer, but this looks like a windows issue, and unfortunately (fortunately?) I have not used windows in well over a decade. 

Try DUMLdore, it has racer built in, and can probably work around this, but I have no idea on windows issues.
