### ISSUE TITLE
Brief elaboration on problem

### ISSUE THREAD

**Issue by Microwave89** [CunningLogic/DUMLRacer#9]
Hi jcase, thank you very much for this SW.
Worked like a charm on MacOS and 01.04.0300 FW of Mavic Pro Platinum (Downgraded from 01.04.0500 first ;) )

I'm eager to know how this works in the first place, everyone is talking about a race in the update system.
What in particular are we racing against?
Why is there 2 races that must be won? Where does the privilege escalation take place?
Is there a problem with the DUML or its interpretation?
Is there a detailed Whitepaper on it or may you give me some pointers? Of course if you couldn't explain without getting too technical then still go ahead and I will still attempt to understand and possibly read up on Android internal workings.

Sincerely Yours,
Microwave89

**Comment by CunningLogic** [comment]
first race places a symlink and moves it out of danger of being deleted, second race moves symlink back into place after the deletion so it can be overwritten.

**Comment by revengi** [comment]
Hi, it is not work a new fw mavic 00.0700, 00.0800, can u fix it?

**Comment by CunningLogic** [comment]
Dont reopen issues to submit non relevant comments. This is a 5yr old project that i am done working on, you are welcome to submit pull requests if you want to change something.

**Comment by CunningLogic** [comment]
closed.
